project: 
  type: website

website: 
  page-navigation: true
  title: 'AGATE' 
  site-url: "https://sfregosi.github.io/agate" 
  repo-url: "https://github.com/sfregosi/agate"
  repo-actions: [issue]
  favicon: images/favicon.ico
  
  page-footer:
    right: 'This page is built with [Quarto](https://quarto.org/).'
    left: '&copy; CC-1.0'
  
  sidebar:
    background: $beaver-orange
    # logo: "https://raw.githubusercontent.com/nmfs-opensci/assets/main/logo/nmfs-opensci-logo3.png"
    favicon: images/favicon.ico
    pinned: true
    align: center
    tools: 
      - icon: github
        href: https://github.com/sfregosi/agate
        text: 'agate'

    style: 'docked'
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Home
      # - href: about.qmd
      #   text: About
      - href: get-started.qmd
        text: Get started
      - href: configuration.qmd
        text: Configuration guide
      - href: plotting-functions.qmd
        text: Plots
      - href: mission-planning.qmd
        text: Mission planning
      - href: piloting-functions.qmd
        text: Piloting
      - href: mission-processing.qmd
        text: Post-mission processing
      - href: convert-acoustics.qmd
        text: Convert acoustic files
      # - href: content/code.qmd
      #   text: Code in your files
      - href: contribute.qmd
        text: Contribute
      - href: acknowledgements.qmd
        text: Acknowledgements

format:
  html:
    theme:
      light: theme.scss
      dark: [cosmo, theme-dark.scss]
    code-copy: true
    code-overflow: wrap
    toc: true
    toc-depth: 4
    link-external-newwindow: true
    embed-resources: true

filters:
  # - include-files.lua
  - quarto

  
